ajout de statut
Aziz19979/HCERES pull request #32
Opened 2023-02-03 15:00 UTC by IkrameHAD

2023-02-04 10:19 UTC, Aziz19979 requested changes

2023-02-04 10:19 UTC, Aziz19979 commented on hceres/src/main/java/org/centrale/hceres/items/TypeActivity.java
> +        TEAM(42);
Why add team as new activity ?
->remove

2023-02-04 10:19 UTC, Aziz19979 commented on hceres/src/main/java/org/centrale/hceres/service/TeamService.java
> +        */
Remove useless commented code,
laboratoryId attribute is not set which is mandatory for team creation :

>         team.setLaboratoryId(RequestParser.getAsInteger(request.get("laboratoryId")));

and use teamRepo to save the new created team
>         teamRepo.save(team);

test of creation should be tested in junit test or postman request or react form.

2023-02-04 10:19 UTC, Aziz19979 commented on doc/code-generator/entities/Team/TeamForm.csv
> +teamLastReport, date, teamLastReport, "", team.teamLastReport
data label column should be translated into french,
for example:
Nom de l'équipe
Date de création d'équipe
Date de fin d'équipe
dernier rapport de l'équipe

2023-02-04 10:19 UTC, Aziz19979 commented on hceres-frontend/src/components/Researcher/Researcher.js
> +                {
make parenthesis on same line,
....
                    return statusName;
                },
            }, {
                dataField: 'actionColumn',

2023-02-04 10:19 UTC, Aziz19979 commented on hceres/src/main/java/org/centrale/hceres/items/BelongsTeam.java
> +
try to impact as less files as you can when commit, remove addition of white line

2023-02-04 10:19 UTC, Aziz19979 commented on hceres/src/main/java/org/centrale/hceres/service/TeamService.java
> +    */
remove useless activities related code

2023-02-04 10:19 UTC, Aziz19979 commented on hceres/src/main/java/org/centrale/hceres/controller/TeamController.java
> +import java.text.ParseException;
turn on sonar lint to fix code smell.
for example here remove unused import 
import org.centrale.hceres.items.Activity;
import java.text.ParseException;
import java.util.Optional

2023-02-08 14:58 UTC, Ahmad-Said approved these changes

2023-02-08 14:59 UTC, Aziz19979 approved these changes

2023-02-08 14:59 UTC, merged